version: "3.9"

services:

  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular19-ui
    ports:
      - "8080:80"
    depends_on:
      - node-api
    restart: unless-stopped

  node-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data: