version: '3.9'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular19-ui
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped